Improve JSON parsing (thanks, Pandas 0.24!)
Should fix error on production:

Exception in loadurl.fetch
Traceback (most recent call last):
  File "/app/server/models/loaded_module.py", line 209, in fetch
    out = await future_result
  File "/app/server/modules/loadurl.py", line 81, in fetch
    result = parse_bytesio(bytes_io, mime_type, charset)
  File "/app/server/modules/utils.py", line 399, in parse_bytesio
    return _safe_parse(bytesio, parser, text_encoding)
  File "/app/server/modules/utils.py", line 145, in _safe_parse
    return ProcessResult.coerce(parser(bytesio, text_encoding))
  File "/app/server/modules/utils.py", line 249, in _parse_json
    return pandas.DataFrame.from_records(data)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 1554, in from_records
    mgr = arrays_to_mgr(arrays, arr_columns, result_index, columns)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 51, in arrays_to_mgr
    index = extract_index(arrays)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 320, in extract_index
    raise ValueError('Mixing dicts with non-Series may lead to '
ValueError: Mixing dicts with non-Series may lead to ambiguous ordering.

This changes loadurl to no longer use the "sfpd.json" data file. Those
tests were near-impossible to maintain, because they did not explain what
we wanted.