INSERT AddTabCommand *then* DELETE soft-deleted tabs
Should solve this error on production:

Traceback (most recent call last):
  File "./server/handlers/decorators.py", line 101, in inner
    data = await task
  File "./server/handlers/tab.py", line 96, in create
    await AddTabCommand.create(workflow=workflow, slug=slug, name=name)
  File "./server/models/Delta.py", line 211, in create
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 108, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/channels/db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 123, in thread_handler
    return self.func(*args, **kwargs)
  File "./server/models/Delta.py", line 264, in _first_forward_and_save_returning_ws_data
    delta.forward_impl()
  File "./server/models/commands/AddTabCommand.py", line 55, in forward_impl
    self.tab.save(update_fields=['is_deleted'])
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 909, in _save_table
    raise DatabaseError("Save with update_fields did not affect any rows.")
django.db.utils.DatabaseError: Save with update_fields did not affect any rows.

The way to get that error:

1. Add a tab
2. Undo
3. Add another tab

(Ditto WfModule, which was probably more common.) We've seen this crash
four times.