Fix duplicating reports [finishes #176474936]
The error we're fixing: previously, duplicating a workflow would
always set the duplicate's has_custom_report to False, even if there was
a custom report. Afterwards, editing the report would cause an error
because we'd try to create the auto-report ... and a report already
existed.

There's a migration to set has_custom_report=True wherever we're sure
this bug occurred. We'll mis-duplicate custom+empty reports, but that
probably won't affect many users.

Should fix this error on production:

Traceback (most recent call last):
  File "./server/handlers/decorators.py", line 109, in inner
    data = await task
  File "./server/handlers/report.py", line 65, in add_block
    await commands.do(
  File "./cjwstate/commands.py", line 204, in do
    ) = await _first_forward_and_save_returning_clientside_update(
  File "./cjworkbench/sync.py", line 48, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/channels/db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 343, in thread_handler
    return func(*args, **kwargs)
  File "./cjwstate/commands.py", line 118, in _first_forward_and_save_returning_clientside_update
    command.forward(delta)
  File "./cjwstate/models/commands/add_block.py", line 66, in forward
    auto_block.save()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "unique_workflow_block_slugs"
DETAIL:  Key (workflow_id, slug)=(124220, block-auto-step-tss8EmOS588j) already exists.