formula: catch DispatcherError
Should fix error on production:

Failed DISPATCHING 'DATE' due to:
  FunctionError('Function not implemented!')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/schedula/utils/sol.py", line 620, in _evaluate_node
    **kw)
  File "/usr/local/lib/python3.7/site-packages/schedula/utils/sol.py", line 594, in _evaluate_function
    sol=self, callback=_callback, sol_name=self.full_name + (node_id,)
  File "/usr/local/lib/python3.7/site-packages/schedula/utils/asy.py", line 167, in async_process
    name, funcs, executor, *args, **kw
  File "/usr/local/lib/python3.7/site-packages/schedula/utils/asy.py", line 124, in _process_funcs
    r['res'] = e.process(fn, *args, **kw) if e else fn(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/formulas/functions/__init__.py", line 81, in not_implemented
    raise FunctionError()
formulas.errors.FunctionError: Function not implemented!