Fix delete of workflows without init
_Should_ fix error on production -- but I didn't manage to trigger it
with my unit test. I think the error is pretty clear: we tried to delete
an already-deleted Delta. So I'm surprised my unit test didn't pick it
up.

Traceback (most recent call last):
  File "/app/server/cron/__init__.py", line 61, in delete_expired_sessions_and_workflows_forever
    'delete_expired_sessions_and_workflows()')
  File "/app/server/cron/__init__.py", line 25, in benchmark
    return await task
  File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 108, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/channels/db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 123, in thread_handler
    return self.func(*args, **kwargs)
  File "/app/server/cron/sessions.py", line 13, in delete_expired_sessions_and_workflows
    delete_expired_sessions_and_workflows_sync()
  File "/app/server/cron/sessions.py", line 47, in delete_expired_sessions_and_workflows_sync
    workflow.delete()
  File "/app/server/models/Workflow.py", line 282, in delete
    self.clear_deltas()
  File "/app/server/models/Workflow.py", line 276, in clear_deltas
    second_delta.delete()  # will CASCADE to delete all subsequent deltas
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 967, in delete
    (self._meta.object_name, self._meta.pk.attname)
AssertionError: ChangeParameterCommand object can't be deleted because its delta_ptr_id attribute is set to None.