notifications: handle when `stale_crr is None`
Fixes error on production:

Traceback (most recent call last):
  File "/app/worker/render.py", line 135, in handle_render
    workflow_id, delta_id)
  File "/app/worker/util.py", line 8, in benchmark
    return await task
  File "/app/worker/render.py", line 76, in render_or_requeue
    workflow_id, delta_id)
  File "/app/worker/util.py", line 8, in benchmark
    return await task
  File "/app/worker/execute/workflow.py", line 88, in execute_workflow
    result = await execute_tab_flow(workflow, tab_flow, tab_shapes)
  File "/app/worker/execute/tab.py", line 136, in execute_tab_flow
    last_result, tab_shapes)
  File "/app/worker/execute/wf_module.py", line 205, in execute_wfmodule
    output_delta = await _execute_wfmodule_save(workflow, wf_module, result)
  File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 108, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/channels/db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/asgiref/sync.py", line 123, in thread_handler
    return self.func(*args, **kwargs)
  File "/app/worker/execute/wf_module.py", line 106, in _execute_wfmodule_save
    stale_result = stale_crr.result
AttributeError: 'NoneType' object has no attribute 'result'