Downgrade pyroute2
*Somehow* fixes crazy error:

django.db.utils.DataError: malformed array literal: "[[1, 1]]"
LINE 1: ...ule_id", "old_version", "new_version") VALUES (2, '[[1, 1]]'...
                                                             ^
DETAIL:  "[" must introduce explicitly-specified array dimensions.

... Somehow, something in pyroute2 was messing with Django innards?
(I've learned that Django SQL is not _real_ SQL: it's JSON-encoded
values that get decoded and re-encoded as Postgres-compatible SQL.
Except, with a newer pyroute2 they aren't....)