Allow Pandas modules to return {"message":...} errors
Previously, they needed {"message":..., "quickFixes": ...}.

Should fix error on production:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyspawner/main.py", line 81, in run_child
    child_main(*args)
  File "/app/cjwkernel/pandas/main.py", line 26, in main
    run_in_sandbox(compiled_module, function, args)
  File "/app/cjwkernel/pandas/main.py", line 71, in run_in_sandbox
    result = module.render_thrift(*args)
  File "/app/cjwkernel/pandas/module.py", line 282, in render_thrift
    arrow_result: types.RenderResult = __render_by_signature(
  File "/app/cjwkernel/pandas/module.py", line 248, in __render_by_signature
    return fn(
  File "/app/cjwkernel/pandas/module.py", line 105, in __render_pandas
    result = ptypes.ProcessResult.coerce(
  File "/app/cjwkernel/pandas/types.py", line 967, in coerce
    return cls._coerce_2tuple(value, try_fallback_columns)
  File "/app/cjwkernel/pandas/types.py", line 989, in _coerce_2tuple
    errors = ProcessResultError.coerce_list(error)
  File "/app/cjwkernel/pandas/types.py", line 744, in coerce_list
    return [cls.coerce(error) for error in error_or_errors]
  File "/app/cjwkernel/pandas/types.py", line 744, in <listcomp>
    return [cls.coerce(error) for error in error_or_errors]
  File "/app/cjwkernel/pandas/types.py", line 767, in coerce
    raise ValueError("Missing 'quickFixes' in %s" % value)
ValueError: Missing 'quickFixes' in {'message': I18nMessage(id='errors.valueNotTimestamp', arguments={'colname': 'Week of', 'value': '0'}, source='module')}