Bump cjwmodule, leading to a bump in httpx
May fix an error we've seen in production:

h11._util.LocalProtocolError: Can't send data when our state is ERROR
    at send_with_data_passthrough (/usr/local/lib/python3.8/site-packages/h11/_connection.py:484)
    at send (/usr/local/lib/python3.8/site-packages/h11/_connection.py:469)
    at send (/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py:466)
    at main_wrap (/usr/local/lib/python3.8/site-packages/asgiref/sync.py:212)
    at __get_result (/usr/local/lib/python3.8/concurrent/futures/_base.py:388)
    at result (/usr/local/lib/python3.8/concurrent/futures/_base.py:432)
    at __call__ (/usr/local/lib/python3.8/site-packages/asgiref/sync.py:147)
    at handle (/usr/local/lib/python3.8/site-packages/channels/http.py:250)
    at thread_handler (/usr/local/lib/python3.8/site-packages/asgiref/sync.py:343)
    at run (/usr/local/lib/python3.8/concurrent/futures/thread.py:57)
    at wait_for (/usr/local/lib/python3.8/asyncio/tasks.py:455)
    at __call__ (/usr/local/lib/python3.8/site-packages/asgiref/sync.py:304)
    at __call__ (/usr/local/lib/python3.8/site-packages/channels/http.py:192)
    at __call__ (/usr/local/lib/python3.8/site-packages/uvicorn/middleware/asgi2.py:7)
    at __call__ (/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py:45)
    at run_asgi (/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py:389)