minio: correctly raise FileNotFoundException
Should fix error on production (when trying to diff a fetch result
against a CachedRenderResult that never got written because OOM):

Error during render
Traceback (most recent call last):
  File "/app/worker/render.py", line 138, in handle_render
    workflow_id, delta_id)
  File "/app/worker/util.py", line 8, in benchmark
    return await task
  File "/app/worker/render.py", line 77, in render_or_requeue
    workflow_id, delta_id)
  File "/app/worker/util.py", line 8, in benchmark
    return await task
  File "/app/worker/execute/workflow.py", line 97, in execute_workflow
    result = await execute_tab_flow(workflow, tab_flow, tab_shapes)
  File "/app/worker/execute/tab.py", line 143, in execute_tab_flow
    tab_shapes)
  File "/app/worker/execute/wf_module.py", line 222, in execute_wfmodule
    output_delta = await _execute_wfmodule_save(workflow, wf_module, result)
  File "/app/cjworkbench/sync.py", line 46, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 388, in wait_for
    return await fut
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/channels/db.py", line 14, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/asgiref/sync.py", line 169, in thread_handler
    return func(*args, **kwargs)
  File "/app/worker/execute/wf_module.py", line 115, in _execute_wfmodule_save
    stale_result = stale_crr.result
  File "/app/server/models/CachedRenderResult.py", line 116, in result
    dataframe = self.read_dataframe()
  File "/app/server/models/CachedRenderResult.py", line 89, in read_dataframe
    args, kwargs
  File "/app/server/parquet.py", line 123, in read
    pf = read_header(bucket, key, open_with=open_with)
  File "/app/server/parquet.py", line 101, in read_header
    filelike = open_with(bucket, key)  # raises FileNotFoundError
  File "/app/server/parquet.py", line 57, in _minio_open_full
    return minio.FullReadMinioFile(bucket, key)
  File "/app/server/minio.py", line 426, in __init__
    transfer.download_file(self.bucket, self.key, tf.name)
  File "/usr/local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/usr/local/lib/python3.7/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/usr/local/lib/python3.7/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/s3transfer/tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/s3transfer/download.py", line 345, in _submit
    **transfer_future.meta.call_args.extra_args
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found